### ISSUE TITLE
Unnecessary column in TPC-H 6

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1115]
What do we need those projections for? The value is constant and should be directly put into the PredicateNode.

<img width="503" alt="screen shot 2018-09-11 at 18 52 05" src="https://user-images.githubusercontent.com/575106/45374941-dd57cf80-b5f3-11e8-9e51-6d92da996f24.png">

**Comment by mrzzzrm** [comment]
Originally, the existence of this column in this Projection is justified, since it's the only way the SQLTranslator has to make sure that the Predicate above can be evaluated.

Then, the ConstantCalculationRule comes along and removes the necessity for this column, without however removing any now-useless temporary columns.

(There is indeed a bug in here, as the ConstantCalculationRule should actually rewrite `0.06-0.01` to `0.05` in the Projections as well, but doesn't. This is because the rule relies on `node_expressions()` to query for all expressions used. `node_expressions()` returns a vector of expressions **by value** thus making it impossible to rewrite the root operation of an expression.)

With evaluate_to_poslist temporary columns like this will not be necessary anymore.

**Comment by mrks** [comment]
> With evaluate_to_poslist, temporary columns like this will not be necessary anymore.

Sounds good. Should we keep an issue somewhere where we collect all the things that should be fixed with that?
