### ISSUE TITLE
Handle Null-Values in Columns

### ISSUE THREAD

**Issue by jstriebel** [hyrise/hyrise#13]
In the [TPC-C specification](http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-c_v5.11.0.pdf) null values are needed in the generated tables (see p. 68).

This is needed for
* the [ORDER Table, column O_CARRIER_ID](https://github.com/hyrise/zweirise/blob/mp/feature/tpcc-benchmark/src/benchmark-libs/tpcc/table_generator.cpp#L317), and
* the [ORDER-LINE table, column OL_DELIVERY_D](https://github.com/hyrise/zweirise/blob/mp/feature/tpcc-benchmark/src/benchmark-libs/tpcc/table_generator.cpp#L357)

**Comment by lawben** [comment]
How do we want the export/import of null values to work in binary? At the moment we just write the value to binary but that won't work with nullable values because we could not distinguish between an empty string `""` and `null` or between `0`and `null` and so on. 

I could image two approaches to solve this problem:
 - write a list of `bool` before the column values indicating whether they are `null` or not. This is similar to `string_lengths` that are written now to tell the parser how long each string is.
 - write an additional byte (`bool`) in front of each value indicating `null` or `not null`. This would basically be a pair of `(is_null, value)`

Do you have any preferences or further suggestions on how to do this? I prefer the first option slightly, as it maps directly to our column with the `_null_values` vector, so this could be created in one go.

**Comment by Bensk1** [comment]
In case we implement the first option. Could we also write a bit mask before the column values to save storage space?

**Comment by mrks** [comment]
And then only write positions that have a values? Nice thinking, but I believe it makes the implementation more complicated, more expensive  (b/c you can't read the vector into memory 1:1), and more difficult to parallelize (b/c you have no offsets).

**Comment by mrks** [comment]
We should check if we have the correct NULL semantics everywhere.

**Comment by mrks** [comment]
@lawben There are two operators left on the list. `IndexScan` should be refactored anyway. `Difference` cannot be used in SQL right now anyway, because all translations are missing. As argued in #160, I think we can postpone thinking about those multiset operators (union/difference/intersect) once we actually end up needing them.

For now, I think it should be enough to add non-debug assertions to those operators that make sure that they do not operator on non-null columns.
