### ISSUE TITLE
Transactions with failed operators can be committed

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1393]
Example:

src/test/operators/delete_test.cpp
```
@@ -184,7 +184,7 @@ TEST_F(OperatorsDeleteTest, UpdateAfterDeleteFails) {

   delete_op->execute();

-  t1_context->commit();
+  ASSERT_FALSE(t1_context->commit());
```

(1) This should fail.
(2) Operators should not execute if it is known that the transaction is a goner.
(3) Enforce checking of the transaction result: `[[nodiscard]] bool TransactionContext::commit();`
(4) If `commit()` fails the transaction should have already been rolled back. This should be covered by an assertion.

**Comment by d-justen** [comment]
I have looked into this now, and for me it is not clear, why this should fail. If I understand this test correctly, the deletion is supposed to work fine, but only the update that comes after should fail, because its rows to update are already deleted. 
Trying to commit this update actually does fail, because of the DebugAssert in `_prepare_commit()`:
```
DebugAssert(([this]() {
                for (const auto& op : _rw_operators) {
                  if (op->state() != ReadWriteOperatorState::Executed) return false;
                }
                return true;
              }()),
              "All read/write operators need to be in state Executed (especially not Failed).");
```
But I guess then the `commit()` should rather return false, than to raise an exception, right? 

Regarding (4): If you are trying to commit a transaction that is already rolled back, you will get a logic error, because it is an illegal phase transition (the transaction context will try to transition from RolledBack to Commiting). Isn't this the wanted behavior? Or is this a misunderstanding and the operators are actually supposed to rollback the transaction, if they fail?

**Comment by mrks** [comment]
It actually appears as if the situation is not as bad as originally expected. I am having some trouble defining what the expected / best behavior is, though.

> But I guess then the commit() should rather return false, than to raise an exception, right?

Correct. During regular execution, we should never see a single exception, even if we have a transaction conflict. After all those conflicts are expected to some degree.

Here's what we have:
1. Once a Tx is known to have failed, operators that were already scheduled should not be executed. This is already done in abstract_operator.cpp.
2. `SQLPipeline::get_result_tables` checks whether the context has been aborted and returns an empty result table.

What I think should change:
1. The return value of `commit()` should not be ignored.
2. No new operators should use a failed Tx. This can be asserted in `AbstractOperator::set_transaction_context`, but in the end, it's the caller's responsibility. Usually, this probably means that the SQLPipeline should check for the state of the transaction before running the next SQLPipelineStatement.
3. This requires the caller (usually the pipeline) to check the state after each statement and before calling commit. Once we have that, that logic error described in your question should not occur anymore.
4. We should have some tests that use the SQLPipeline end-to-end and test the handling of commits and rollbacks. The conflicts that we currently simulate in the tests are not showing the whole picture.

I am not sure if this answers all questions and covers all aspects. Please let me know if any of this does not make any sense.

**Comment by d-justen** [comment]
I've changed the `commit()`-method now to `[[nodiscard]]`. SQLPipelineStatement uses it in `get_result_table()`, but there it doesn't really matter if it fails or not, because it gets the result_table out of the output of the last operator, which would be `nullptr` anyways, if the transaction has failed. I'm not sure what to do then with the commit-result. I could just wrap it in a lambda to actually discard the return value, but I guess then there isn't really a point in using `[[nodiscard]]`.

If I get that right, #2 and #3 are already part of the code, SQLPipeline always checks for the transaction status after every SQLPipelineStatement execution.

**Comment by mrks** [comment]
`nullptr` is also returned for DDL statements (e.g., CREATE TABLE) and DML statements (DELETE), correct? We should distinguish from the "no result case" and the "execution failed/rollback" case. Maybe the user of the pipeline should check for `pipeline_failed()` before retrieving the result table. If the pipeline failed, retrieving the table should throw an exception.

**Comment by engelfa** [comment]
#1493

**Comment by d-justen** [comment]
Yes, that's correct.

There's one thing that still isn't really clear to me: If an operator fails and the transaction context is committed anyway, is the context supposed to raise an exception or to just return false? And can there be other reasons that cause a transaction commit to fail, if all the operators are executed?

**Comment by mrks** [comment]
Let me answer the second question first.

> And can there be other reasons that cause a transaction commit to fail, if all the operators are executed?

Yes, with #1416, an insert may fail if someone else committed a conflicting unique value first.

> If an operator fails and the transaction context is committed anyway, is the context supposed to raise an exception or to just return false?

Since the caller has no way to check if commit is guaranteed to succeed (see above), we will need to return false and enforce the usage of that return value with nodiscard.
