### ISSUE TITLE
Optimization Rule to avoid performing the same Projection multiple times

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1470]
TPC-H 1 might benefit from this

```
      sum(l_extendedprice*(1-l_discount)) as sum_disc_price,
      sum(l_extendedprice*(1-l_discount)*(1+l_tax)) as sum_charge,
```

**Comment by mrks** [comment]
Is this an optimizer thing though? I would say that it is the expression evaluators job. That's what I built a while ago, but it didn't really change anything. If I remember correctly, too little to even open up a PR. I can push the corresponding branch (mrks/exprcache) if you want to have a look.

The problem is that the materialization is the dominating factor here. Once the input columns are materialized, calculating the subtraction and the multiplication is irrelephant.

**Comment by mrks** [comment]
As mentioned above, this is largely due to the humongous cost of materializing the values - not so much the actual calculation.

**Comment by mrks** [comment]
At least that's what I would expect the profiler to show.

**Comment by Bouncner** [comment]
Yeah, but the join materializes the same values plus the whole orders table and does significantly more work.

**Comment by mrks** [comment]
Remember that the Projection materializes *every* column (of course except for those that were already filtered out). Does that change your estimation?

**Comment by Bouncner** [comment]
That would be only `l_quantity` in this case, right (assume the non-joining query)?

**Comment by Bouncner** [comment]
Hmm ... ok. I overlooked the aggregation.

I don’t like that performance. :-(
