### ISSUE TITLE
Rewrite subqueries if left side is not a column

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1547]
Optimize queries like
```sql
SELECT * FROM customer WHERE c_custkey + 2 IN (SELECT o_orderkey FROM orders)
```
by using a semijoin.

**Comment by mrzzzrm** [comment]
any TPC-something query where we're seeing this kind of pattern?

**Comment by janetzki** [comment]
At least not in the TPC-H benchmark. What comes closest is the TPC-H 11:
```sql
...
HAVING SUM(ps_supplycost * ps_availqty) > (
    SELECT SUM(ps_supplycost * ps_availqty) * [FRACTION]
...
```
This query would be optimizable if the comparator were a `=`.

**Comment by mrks** [comment]
`SELECT SUM(ps_supplycost * ps_availqty) * 0.0001 FROM partsupp, supplier, nation WHERE ps_suppkey = s_suppkey AND s_nationkey = n_nationkey AND n_name = 'GERMANY'` is not correlated, so it is executed as a ColumnVsValueScan.

If we find an example for this in the TPC-DS, we should certainly look into optimizing it. Until then, there are plenty of things that could be optimized, so we should either open an aggregator issue for all queries where we see some untapped optimization potential or simply wait for those optimization issues to pop up. I vote to close this for now in order to keep the issue list small.

*We once were sad when it spilled on a second page. :(*

**Comment by janetzki** [comment]
I'm also fine with closing this issue.
