### ISSUE TITLE
Extending RowID to include table identifiers?

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#160]
As @TwoLaid and @SvenLehmann mentioned last week, we still don't have a clear solution for joins, where we combine tuples from multiple tables (e.g., after a union) and chunks.

One solution would be to create chunks for every single combination, but that's ridiculous (@TwoLaid: i think you guys benchmarked this, correct?).
Another one would be to have a table identifier as part of the RowID (e.g., 16 bit for the table, 16 for the table's chunks, and the remaining 32 for the row number in the chunk).

We skipped the problem for the seminar, but we probably need to address it at some point in time.

Any comments?

**Comment by mrks** [comment]
If I am not mistaken, this is not about "combin[ing] tuples from multiple tables (**e.g.**, after a union) and chunks" but *exactly* about how we handle `UNION [ALL]`.

In the Sprint document, we write:
> Because a ReferenceColumn cannot point to values in different tables (e.g., because two tables were concatenated using a union), we could not use the same approach for the sort operator if the first chunk was part of a different table. In this case, we will resort to materializing the inputs.
If we extend this to also include joins after unions, this still holds true.

1) this is only a problem that occurs when we actually use `UNION`. In all the months since this is open, it has not occured anywhere else.
2) we have never needed `UNION` so far and TPC-H does not use it.
3) this will significantly increase the memory footprint of ReferenceColumns.
4) materializing the result of union in case it touches different tables is enough to guarantee correctness.

As a result, I believe that it should be enough to add an assertion to the current `UnionAll` that makes sure that both tables are the same. **If** we need to union different tables in the future, we can still write the materialization.

Close?

**Comment by Bouncner** [comment]
The topic came up during the join tests, not during the union. (i) yes, I cannot come up with another instance of the problem, (ii) that's does not really solve the problem :-/, (iii) as written in the first post, we could use the first half of the rowid to include a table AND the chunkID, thus not needing more space, (iii) yes, but I am not aware of any way to do that in an efficient manner.

Maybe we should discuss this topic in person.

**Comment by mrks** [comment]
Reading my answer above again I feel that the most important point is underrepresented:

This is a lot of work. We need to touch all operators to make sure that they can handle the new format. It makes understanding ReferenceColumns more difficult than it already is and will make optimization more complicated, too. Think about the discussion that we have about order PosLists right now.

As of now, I believe it is not worth putting in time to support an edge case that is entirely preventable and will, as far as we know right now, never be executed.

I put it on my Todo list for tomorrow and we can talk about it again.

**Comment by mrks** [comment]
One more thing: All operators would have to check the table id for every row. This would make the hot loop more expensive.

We discussed this after the round table and found that (a) we don't need this feature right now and (b) delaying this decision will not help us in the future.

If we really need this for some benchmark, we can still revisit it.

**Comment by Bouncner** [comment]
Let's keep that issues closed for now, but as I just did a very basic test in HANA for TPC-DS, I found this:
https://github.com/cloudera/impala-tpcds-kit/search?utf8=✓&q=union&type=

At least for TPC-DS, this issue might become problematic again.
