### ISSUE TITLE
FrameOfReference encoding (or vector compression?) cannot handle > UINT_MAX

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1662]
Wanted to add FoR to the JoinTestRunner, which uses values > UINT_MAX, ran into this Assert in the `FrameOfReferenceEncoder`:

```c++
        // Make sure that the largest offset fits into uint32_t (required for vector compression.)
        Assert(static_cast<std::make_unsigned_t<T>>(*max_it - *min_it) <= std::numeric_limits<uint32_t>::max(),
               "Value range in block must fit into uint32_t.");
```

Just disable vector compression if the values are too large for it? 
Why is this Assert in the FoR-Encoder and not in compress_vector()?

**Comment by Bouncner** [comment]
For does not have any advantage if vector compression is disabled.

If I understand you right, you ask why the vector compression does not have the check. I'd guess the reason is that we started with vector compression much much earlier than with the FoR implementation as it is used for the attribute vector in the dictionaries (to encode the dictionary positions with 1/2/4 bytes) and for this vector, we know that the length of the dictionary can never exceed the number of rows per chunk. Hence, uint32_t is just fine and it was never a problem.

Probably we should simply change the vector compression to work on top of a uint64_t vector.
