### ISSUE TITLE
LQPTranslator uses wrong Union for combining the results of Index- and TableScan

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#1711]
The LQPTranslator uses the expensive UnionPositions which is meant for other use cases. Instead, the cheapest possible unioning method (UnionAll) should be used.

**Comment by mrks** [comment]
@d-justen You assigned yourself on this. What is the status?

**Comment by d-justen** [comment]
Well, it's a change in one line to use UnionAll at this place. But I've noticed that UnionNode takes an enum UnionMode, which can only be UnionPositions. I thought of adding at least the option of creating an UnionNode in UnionAll mode. Does this make sense? This shouldn't be a lot of work, but I didn't have the time yet to finish this.

**Comment by mrks** [comment]
Yes. This should be introduced properly in all the translation steps. It just hasn't been done yet as UnionAll was never used (even though it should have).

In fact, we should consider adding translation support for the remaining set operations as well so that we only have to touch those places one.
