### ISSUE TITLE
Table comparison fails if SQLite optimizes column type

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1796]
Using the TPC-DS schema, the query
```sql
SELECT ca_gmt_offset
FROM customer_address
LIMIT 100;
```
leads to different results when compared with `check_table_equal()` because SQLite uses an `int` column while the actual output is a `float` column. `ca_gmt_offset` is defined as `decimal(5,2)` but SQLite seems to optimize the type because it only contains integers.
While this does currently not lead to problems in the verification of TPC-DS queries, it could do so in the future.
An open question is why the TPC-DS specification defined `ca_gmt_offset` as `decimal(5,2)` in the first place.

**Comment by mrks** [comment]
>  An open question is why the TPC-DS specification defined ca_gmt_offset as decimal(5,2) in the first place.

Nepal runs on UTC+05:45.

**Comment by mrks** [comment]
Will be the same issue in #1799. Simply ignore data types when comparing to sqlite?

**Comment by janetzki** [comment]
We could ignore the types only in case SQLite returns an int column, whereas Hyrise returns a float/double column and print a warning that the type cannot be verified.

**Comment by mrks** [comment]
The sqlite TPC-DS schema is not the same as the one in Hyrise, but the one defined in tpcds.sql. This is so that we can use the primary key statements, which Hyrise currently does not support.

If we create a float/double column and insert only ints in the sqlite test, everything is correct.

As this is specific to the TPC-DS, I do not consider this an issue. Feel free to re-open if you disagree.
