### ISSUE TITLE
external processing

### ISSUE THREAD

**Issue by tglanz** [hyrise/hyrise#2033]
Hi,

I was wondering if there is any method to copy data from main memory to an external hardware/other replication target?

Either way, how would i go about implementing such a thing?

Thanks!

**Comment by mrks** [comment]
Depending on what you are trying to achieve, I see two options:

First, we have a binary export for tables. If you can open a FIFO handle, you should be able to write the binary dump of the segments into that stream.

Second, if you are more interested in a logical view of the table rather than the physical representation, it should be relatively easy to write a plugin that has Hyrise on one side and whatever you are writing to on the other.

If you give us more details on what you are trying to achieve, we can discuss which approach should be easier.

**Comment by tglanz** [comment]
the binary export looks as a good start, does it support partial export? for example, overtime, export new chunks of data.

and i will take a closer look at the plugin api.

thank you for the quick response!
