### ISSUE TITLE
float vs decimal precision

### ISSUE THREAD

**Issue by tglanz** [hyrise/hyrise#2272]
hi,

i'm performing tests over the tpch schema which i load it through the generation mechanism and having some inaccuracies.

in tpch the decimal fields (which are floats; such as l_discount) should be with accuracy of 2 decimal places.

now, when i perform of queries using my system, as i can tell, there is a mismatch because the values are floating points; for example, the value that i expect to be 0.05 and which i calculate with, is 0.05007... in hyrise.

my question is, in hyrise, is there a way to constrain accuracy in computations?

**Comment by mrks** [comment]
Hyrise does not support fixed-precision decimals yet. We are following Boncz et al.'s interpretation that "[a]ccording to the TPC-H rules, it is allowed to represent decimals as 64-bits doubles".

The way that I read the TPC-H specification, we might technically have to truncate the result values to the corresponding number of places. That in turn would require us to add a "pretend" decimal type so that we have the number of required decimal places. Given that the TPC-H results are very small and the majority of the work is done beforehand, this will not be of any performance relevance.

As such, simply operating on doubles is one of the liberties that we allow ourselves, being a research DBMS that is not meant to be in production.

If this is going beyond a question to better understand Hyrise (which is absolutely fine) and actually causes problems for you, please let us know and we can try to find a solution.

**Comment by tglanz** [comment]
thanks, i understand.

does hyrise support any ```TRUNC``` equivalent?

**Comment by mrks** [comment]
You can build something similar with the modulo operator:

```
(debug)> SELECT 1.234 - 1.234 % .01
=== Columns
|1.234 - 0.004|
|       double|
|     not null|
=== Chunk 0 ===
|<ValueS>     |
|         1.23|
===
1 rows total
```

Note that this materializes and decompresses the value that you are operating on. If you do this on a relatively small query result, as described above, this should not affect the performance. If you do it somewhere further down in the query plan, this may hurt the performance of following operators.

Also, as a side note, Hyrise does identify common subexpressions, so `(complicated expression) - (complicated expression) % .01` does not lead to the complicated expression being evaluated twice.

**Comment by mrks** [comment]
I'm closing this as it is nothing that we will work on any time soon. Please feel to re-open or open a new issue for follow-up/new questions.
