### ISSUE TITLE
Sort operator does not handle MVCC columns

### ISSUE THREAD

**Issue by mjendruk** [hyrise/hyrise#408]
The sort operator does not copy the MVCC information from the input table. Validation has therefore to happen before.

**Comment by mrks** [comment]
Is this an issue? I can't see a reason why you would want to sort first (which is more expensive if you include unvalidated rows) and validate second. Maybe this should just cause an exception?

**Comment by Bouncner** [comment]
Well, at least the plan building needs to ensure that validate happens (at some point) before. Easy to construct cases where this might cause incorrect results, I think.

Or do I miss sth?

**Comment by mrks** [comment]
Correct. See my response in #409

**Comment by mrks** [comment]
I have given this some more thought. If we do this, we would need to distinguish between R/W and R/O MVCC columns. This is so that no one can pass the MVCC column of a sort result into the delete operator. Also, the R/O column should not have to use atomics.

As far as performance goes, the argument brought forward in #409, saying that it might be better to perform a join on a Value/Dictionary Column rather than a ReferenceColumn, does not really apply here. The only case where we don't have a ReferenceColumn as the input of the sort is if we do `SELECT * FROM foo ORDER BY bla` without any predicates. I don't think that we should spend any time trying to optimize this.

In all other cases (when we already have a ReferenceColumn), executing Validate will have the same number of atomic reads. It might be a bit cheaper if we do it before the sort, because the chance of sequential accesses is still higher.

I will add an assertion to validate that MVCC columns have to be present.
