### ISSUE TITLE
MVCC Physical Delete

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#57]
Rows which are not visible for any running transaction should be deleted at some point. HANA/Hyrise (v1) reorganize during the merge process. Now it must be an additional step because we do not merge. Chunks could get smaller or multiple chunks could be combined into a new chunk.

**Comment by mrks** [comment]
Long-term issue maintained in Trello now

**Comment by mrks** [comment]
Not sure if I am missing something, but it might be possible to have a "cleanup transaction" that deletes all visible rows from chunks that are to be cleaned up and reinsert them at the end of the table. As that Tx commits atomically, we don't have any concurrency issues. Logging might have a special log entry "revalidation" so that we don't have to copy the values.

This would still mean that we would have a list of completely empty chunks (where everything is invalid). By tracking the lowest snapshot commit id across all transactions, we know when no one can reference this chunk anymore. At that point, we release the shared_ptr and either replace it with a tombstone that needs to be skipped or reuse the slot for a later chunk.

**Comment by Bensk1** [comment]
> to have a "cleanup transaction" that deletes all visible rows

Do you mean "that deletes all invisible rows"? 

I think you are right, such a cleanup transaction should avoid possible concurrency issues if I understand correctly what you are describing. This solves the issue of removing invisible rows from chunks, but could lead to a point where we have many small or half empty chunks, right?

**Comment by klauck** [comment]
I think this would work.
However, I agree with @Bensk1 that the actual problem of half/almost empty chunks, which increases scan/validation costs, is not solved.

**Comment by Bouncner** [comment]
Why would there be half-empty chunks to scan? The purpose is to merge exactly those chunks and skip them afterwards when they have been tombstoned, isn’t it?

We move visible rows. I have no idea about transaction handling of that and it will skrew up chances to prune heavily. But it still souds reasonable.

**Comment by mrks** [comment]
> Why would there be half-empty chunks to scan? The purpose is to merge exactly those chunks and skip them afterwards when they have been tombstoned, isn’t it?

Exactly.

**Comment by Bensk1** [comment]
Apparently, we should discuss this offline.
