### ISSUE TITLE
shared_ptr vs Referenz

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#59]
Reference as long as object stays on stack, smart pointer when stored in object

**Comment by mrks** [comment]
> The exception to this rule is when the called function does something that removes that "Instance up in the stack". We had this case in our JoinDetectionRule. But I guess that's too exotic to warrant passing shared_ptrs around by value all the time

Was that because you passed around a shared_ptr by reference or was it because you actually stored that reference somewhere. As long as the current method remains active (and everything above it on the stack does too), I can't see where this would become a problem.

**Comment by mrks** [comment]
Please have a look at this and tell me what you think:
[Flowchart Pointer.pdf](https://github.com/hyrise/hyrise/files/1461407/Flowchart.Pointer.pdf)

**Comment by TwoLaid** [comment]
My first thought was: "the poor student who has to go through the code base and check/fix all of that..."

Otherwise, all paths make sense to me, although I still feel like a flow chart is a bit of an overkill for a guideline. Maybe it's more of a "further read" kinda deal

**Comment by mjendruk** [comment]
> Please have a look at this and tell me what you think:
Flowchart Pointer.pdf

I looked at it and found some things to discuss. I’ll come to your office tomorrow.

**Comment by mrks** [comment]
I'll be on my way to TechEd tomorrow. As of now, I am not planning to come to Potsdam tomorrow. We can either discuss that here, on Skype, or once I'm back (Friday).

**Comment by mjendruk** [comment]
> Please have a look at this and tell me what you think:
Flowchart Pointer.pdf

The green part ("Do I need ownership?") makes sense to me. The most fundamental question is probably whether the object is going to be stored somewhere and used outside of the current call stack.

The left side of the red part (trivial types) is correct, although it doesn’t say anything about larger data structures (`std::vector` etc.). The right side is mostly okay. Although it makes sense to say: if you're sure that you are going to share the ownership, just accept a `shared_ptr` without reference. That’s the case for example in constructors.

The main problem I have is with the no-branch. If an object is internally managed via a `unique_ptr` but ownership is never transferred, it doesn’t make sense in my opinion to expose this implementation detail by passing or returning a const-reference to the underlying `unique_ptr`. In this case, it’s better to accept or return a const& to the object itself (or a const* if the value can be null).

About the blue part: Again, returning a const& `unique_ptr` doesn’t make sense, because you can’t do anything except accessing the object with it (since you can neither copy nor move a const& `unique_ptr`). Returning `const shared_ptr&` makes sense because you may or may not hold a copy of it somewhere.

I have created my own take on a flow chart using some slides by Herb Sutter:
![export-3](https://user-images.githubusercontent.com/2190123/32947780-0520d7ce-cb9d-11e7-8fea-860286b3f939.png)

**Comment by mrks** [comment]
> if you're sure that you are going to share the ownership, just accept a shared_ptr without reference. That’s the case for example in constructors.

Isn't that the "yes, shared"-path?

> The main problem I have is with the no-branch. If an object is internally managed via a unique_ptr but ownership is never transferred, it doesn’t make sense in my opinion to expose this implementation detail by passing or returning a const-reference to the underlying unique_ptr. In this case, it’s better to accept or return a const& to the object itself (or a const* if the value can be null).

I would be fine with changing this to object references. My worry is that if we also allow raw pointers, people will get tempted to do more things with them then just using them for cases where a reference could be null. In the worst case, someone less experienced sees an interface that needs a shared_ptr and creates that from the raw pointer.

**Comment by mjendruk** [comment]
> Isn't that the "yes, shared"-path?
yes, that’s true.

> In the worst case, someone less experienced sees an interface that needs a shared_ptr and creates that from the raw pointer.

This could also happen with references (see visitor pattern for columns). I think this is something that is easily detectable. If we find `std::shared_ptr<*>{*}` or `std::shared_ptr<*>(*)` in the code, we can be sure someone has created a shared pointer from a raw pointer. And couldn’t we tell newcomers: “Don’t create shared pointers from raw pointers. If you end up in a situtation where you need to pass a shared pointer but only you have a raw pointer / reference, there is something wrong with your architecture.”

In most cases, I agree that passing a shared_ptr is a good general rule, especially in public interfaces. I just think in some occasions, such as private methods, it’s not necessary.

**Comment by mrks** [comment]
@Bensk1 - could you chime in on this?

**Comment by Bensk1** [comment]
@mjendruk you are completely right, from an implementation perspective, it does not make sense to return a `const unique_ptr &`. But I am still with @mrks here since we really want to avoid to make people even think raw pointers are a good idea.  Yes, we could educate people and tell them not to do it, but in my opinion the safer way is to restrict using them. However, as Markus said:

> I would be fine with changing this to object references.

agreed.

**Comment by mrks** [comment]
After long discussions and two attempts for pull requests, this seems to be a never-ending story. While I am all for unifying the code style, I feel like this is a lot of effort for only little benefit.

I vote for closing this. Thumbs up/down please!

**Comment by mrzzzrm** [comment]
Currently, we're at 2/3 for closing. You can change constitutions with that kind of majority @mrks
