### ISSUE TITLE
Settings/Knobs Configuration

### ISSUE THREAD

**Issue by Bensk1** [hyrise/hyrise#63]
At some point, we will have certain parameters to configure, for example, the query cache size, the number of threads to spawn etc.

We need a strategy on how to configure these, e.g., at compile time or at run time, in the source code or in a settings file, as command line parameters etc.

Open for discussion

**Comment by mrks** [comment]
Possible knobs:

- Scheduler
- Print operator: Also print MVCC info?
- SQL: Validate / Don't validate
- Chunk size
- NumaPlacementManager parameters

(feel free to add to this list, so that everything is in one place)

**Comment by mrks** [comment]
We might want to move default parameters to settings file so that we can have different configurations for benchmarks etc. This should be managed by one central instance. Also, whenever it makes sense, it should be possible to change them during runtime (e.g., in the console).

Out of my `hyrise_nvm` experience, I am strongly against compile time flags. The number of configurations explodes, CI becomes a pain, development becomes a pain, and everything takes longer.

**Comment by mrks** [comment]
Also, once we have these knobs, they should be included in the output of benchmark results together with the git hash (e.g., the json output that we build for #573). This is so that when we have old benchmark results, we can easily reproduce them.

**Comment by mrks** [comment]
Long-term issue maintained in Trello now
