### ISSUE TITLE
Improve table_scan_test.cpp

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#678]
A seminar group has written a table scan that passed the test suite but produced wrong results in the performance challenge. We should check why the test suite didn't catch that.

**Comment by mrzzzrm** [comment]
https://de.wikipedia.org/wiki/Abgasskandal#Art_der_Manipulation

**Comment by mrzzzrm** [comment]
I doubt this will get attention without details on what this particular seminar group did. That, or close @mrks?

**Comment by mrks** [comment]
https://github.com/toniSta/DYOD_WS1718_Sprint1/pull/2

**Comment by mrks** [comment]
Just discussed this with @Bensk1:

- We executed the benchmark three times and got three different number of rows. This hints to some undefined behavior.
- The problem does not have to be in the TableScan - it might also be in their implementation of the DictionaryColumn. If you can't find something, you could try it with another implentation

**Comment by Bensk1** [comment]
Does that mean that our tests did not recognize it because our dictionary tests are only implemented on a single chunk?

**Comment by nilsthamm** [comment]
No the problem was, that the attribute_id of the dictionary was the same value as the chunk_offset. 
(Because everything was ordered and each value only existed once)
Therefore I will replace the auto generated and ordered test table with two differently shuffled tables with duplicates. (I decided for two tables to cover 2 different chunk sizes.)
