### ISSUE TITLE
Add convenience methods to table class

### ISSUE THREAD

**Issue by mjendruk** [hyrise/hyrise#697]
I have noticed a few common patterns how columns and chunks are accessed in our code base. 

### <span>#</span>1: Iterating over all chunks
```c++
for (ChunkID chunk_id{0}; chunk_id < table->chunk_count(); ++chunk_id) {
  auto chunk = table->get_chunk(chunk_id);
}
```

I propose adding a getter that returns `const std::vector<std::shared_ptr<Chunk>>&` so that we can write:
```c++
for (auto chunk : table->get_chunks()) {
}
```

### <span>#</span>2: Iterating over all chunks to access the same column
```C++
for (ChunkID chunk_id{0}; chunk_id < table->chunk_count(); ++chunk_id) {
  auto column = table->get_chunk(chunk_id)->get_column(column_id);
}
```

I propose adding getter too so that we can write:

```C++
for (auto column : table->get_columns(column_id)) {
}
```

### <span>#</span>3: Accessing a column in a specific chunk in table
```c++
auto column = table->get_chunk(chunk_id)->get_column(column_id);
```

Proposal:
```c++
auto column = table->get_column(chunk_id, column_id);
```
### Remarks
* We could also think about adding method that return indices too:

```c++
for (auto [column, chunk_id] : table->get_columns_with_index(column_id)) {
}
```

* or the chunks too:

```c++
for (auto [column, chunk] : table->get_columns_with_chunk(column_id)) {
}
```

* I'll implement it if this is wanted
* Please feel free to add other patterns that you have encountered.

**Comment by mjendruk** [comment]
@mrks, @mrzzzrm

**Comment by mrzzzrm** [comment]
This sound reasonable.

I want a name for a column in a chunk. Because when I read "get_columns" I expect the return value to be multiple columns and not multiple parts of the same column... You know what I mean, right?
So get_chunk_columns and get_chunk_columns_with_index seems clearer to me - but I know you won't like that and I don't really like it either.

**Comment by mrks** [comment]
Looks good. If we do this, do we want to get rid of the old accessors? For instance, if you want the number of chunks, would you call `table->get_chunks().size()`?

@mrzzzrm: I see the problem. Putting "chunk" and "column" together doesn't solve it for me. Maybe we need to come up with something completely different?

Also, how about we postpone the implementation until all seminar PRs are merged? That should make it more stable.

**Comment by mjendruk** [comment]
> Looks good. If we do this, do we want to get rid of the old accessors? For instance, if you want the number of chunks, would you call `table->get_chunks().size()`?

No I don’t think so. `table->chunk_count()` is still shorter and `get_chunk()` is still needed in other situations.

> @mrzzzrm: I see the problem. Putting "chunk" and "column" together doesn't solve it for me. Maybe we need to come up with something completely different?

Maybe `get_column_chunks`, `get_column_parts`, `get_all_column_parts`, or `get_chunked_column`?

**Comment by mrks** [comment]
I was more thinking of a single, currently unused word.

Something like "columnlet" (a diminutive version of column) ;)

**Comment by Bouncner** [comment]
Mayby "columchen"?

2018-02-16 7:50 GMT+01:00 mrks <notifications@github.com>:

**Comment by mrks** [comment]
As discussed in the Fortnightly:

There are very few places where you would need a chunk without its chunk_id. While structured bindings were proposed, that just looks like a different way to access the chunks - not necessarily thaaat much more convenient anymore.

Favoring "There's Only One Way To Do It" and looking at the fact that no one seemed to care about this since February, we decided to close this.
