### ISSUE TITLE
print vs to_string vs operator<<

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#716]
I feel like we should decide how we want to get a string representation of our classes. Currently, we do all types of things:

```
void AbstractLQPNode::print(std::ostream& out);
std::string to_string(const AllParameterVariant& x);
std::ostream& operator<<(std::ostream& os, const LQPColumnReference& column_reference);
```

I like `to_string` because it is easy to use in tests: `EXPECT_EQ(column_expression1->to_string(), "ColumnID #1 * 2");`
`operator<<` is nice, too, because that's what everyone is used to.
For `print`, I can't come up with something particularly good about it.

**Comment by mrzzzrm** [comment]
I would aggree, but why does the standard way seem to be to overload operator<<? Because of performance we don't need?

**Comment by mrks** [comment]
Probably because it makes `std::cout << mytype` easier

**Comment by mjendruk** [comment]
No, I think the standard way is `operator<<` passes a stream object which makes composing output much easier. If we have a struct or larger class (as in `AbstractOperator::description`) composing the output using `std::string` is slower than `std::stringstream` or in fact any output stream because it to perform dynamic allocations for each temporary string, while streams do not. Also formatting is much easier using a stream so for any more complicated output we would create a `stringstream` anyway.

**Comment by mjendruk** [comment]
how is `to_string` any more hassle-free than `operator<<` ?

**Comment by mrzzzrm** [comment]
```
DebugAssert(condition, "Failed to execute PQP\n" + to_string(pqp));
```

vs

```
#if IS_DEBUG
std::stringstream stream
stream << pqp;
DebugAssert(condition, "Failed to execute PQP\n" + stream.str()
#endif
```

**Comment by mrzzzrm** [comment]
to_string could probably be a template wrapping a call to operator<<(), though

**Comment by mjendruk** [comment]
you mean 
```c++
const auto to_string = [](const auto& value) {
  std::stringstream stream;
  stream << value;
  return stream.str();
}
```

**Comment by mjendruk** [comment]
I see. Well, it would be better if DebugAssert returned a stream anyway so that we could write:

```c++
DebugAssert(condition) << "Failed to execute PQP\n" << pqp
```

**Comment by mrzzzrm** [comment]
Not possible, sadly, since that would mean the message gets evaluated even in Release builds.
If we'd use https://github.com/gabime/spdlog and/or https://github.com/fmtlib/fmt as proposed here: https://github.com/hyrise/hyrise/issues/714 we could use operator<<() to implement the stringification and have Asserts like `DebugAssert(c, "Failed to evaluate PQP {}", pqp)`

**Comment by mjendruk** [comment]
In this case, I’m in favour of the `operator<<` + a `to_string` method just like I proposed above. This gives us the benefit of both. The only thing is that `operator<<` would have to be virtual in some instances.

**Comment by mrzzzrm** [comment]
Is that even possible? (virtual operator<<)?
Or would it need a virtual _on_operator_lt_lt()

**Comment by mrks** [comment]
Iirc, operator<< needs to be overwritten outside of any namespace or class, so virtual is not an option.

**Comment by mjendruk** [comment]
> Or would it need a virtual _on_operator_lt_lt()

Probably

**Comment by mrzzzrm** [comment]
So there seems to be some consensus here: Go for operator<< as base implementation, provide opossum::to_string for convenience and have a method with a standard name for virtual implementations. 
The question that remains: Which standard name? `_on_operator_lt_lt`? `_on_stream`? @mjendruk

**Comment by mjendruk** [comment]
Adding some ideas: `_output`, `_to_stream`, `stream_output` ?

**Comment by mrzzzrm** [comment]
`_output_to_stream` over `_to_stream`?
