### ISSUE TITLE
Base Index 1 for TPCH Queries

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#791]
So that `tpch_queries[9]` would actually be TPCH query 9, and not 10. 

I am indecisive on this. On the one hand using the 0 base index, as we currently do, for something that is 1-base-indexed (like the TPCH queries) is inconsistent.
On the other hand, someone who just reads `tpch_queries[9]` will expect it to query the 10th element in the array - and he/she would be confused as well if it didn't return the query he/she expected.
Sometimes it pays to stick to painful principles and one of them is that C++ has a base index of 0.

Opinions?

**Comment by lawben** [comment]
I would prefer a 1-based index. I've accidentally spent quite a while debugging the wrong query already just because of this of-by-one confusion. Maybe we should just move the queries into a map instead of an array. Then we can just access TPCH Query 1 at 1 and don't have to worry about this crap :)

**Comment by Bouncner** [comment]
Doesn't a map fit best anyways as we do not yet support all TPC-H queries? Or did I miss that milestone?

**Comment by mrzzzrm** [comment]
I like the map idea to some extend.

**Comment by mrks** [comment]
Works for me

**Comment by mrzzzrm** [comment]
a map its gonna be, as soon as I get to it. Anybody feel free to take this.

**Comment by lawben** [comment]
@mrzzzrm i'll take over in this if you don't mind

**Comment by mrzzzrm** [comment]
do it
