### ISSUE TITLE
Fix memory leaks in ChunkCompression

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#836]
Currently, when generating a table of 4GB, the memory usage after generating the ValueColumns is roughly 4GB.
After compressing the Chunks with DictionaryCompression, the memory usage is about 5.9GB (see #835).

I'm self-assigning this since I am on this right now anyway, but if anyone knows where the problem is, feel free to point it out.

**Comment by Bouncner** [comment]
How is data generated?

For highly distinct sets, dict can actually end up consuming twice the memory compared to uncompressed.

**Comment by lanice** [comment]
In this example, uniformly distributed values from 0 to 10000. But in order to exclude this possibility I tested it with all the same values for a 1GB table:
```
ColumnDataDistribution config = ColumnDataDistribution::make_uniform_config(0.0, 1);
auto table_1 = table_generator->generate_table(std::vector<ColumnDataDistribution>{config}, 250000000, 2500000, std::nullopt);
```
results in ~1GB
```
ColumnDataDistribution config = ColumnDataDistribution::make_uniform_config(0.0, 1);
auto table_1 = table_generator->generate_table(std::vector<ColumnDataDistribution>{config}, 250000000, 2500000, EncodingType::Dictionary);
```
results in ~1.3GB

**Comment by lanice** [comment]
The `use_count` of the shared pointers holding the value columns drop from 2 to 1 (it counts "itself" as well) after `ChunkEncoder::encode_all_chunks` in the TableGenerator, and should drop to 0 after going out of scope there, so it *should* be destroyed...

**Comment by mrks** [comment]
Remember that free'd memory [is not necessarily returned to the OS](https://stackoverflow.com/questions/2215259/will-malloc-implementations-return-free-ed-memory-back-to-the-system).

We really need #682...

**Comment by mrks** [comment]
Thanks to shared pointers, we don't have actual leaks, but only lifetimes that are too long. Two tests show that this is not the case in this instance:

First, good old printf debugging, printing the construction and deconstruction of ValueColumns:

```
- Generating TPCH Tables with scale_factor=0.001...
 ValueColumn
 [60 times more]
~ValueColumn
 [60 times more]
- Done.

- Starting Benchmark...
```

So we can see that those are gone.

Second I stripped down the dictionary encoder to ignore every incoming value so that it returns an empty column. After encoding, I added a 20s sleep so that we can actually see something:

<img width="778" alt="screen shot 2018-06-26 at 9 32 21 pm" src="https://user-images.githubusercontent.com/575106/41934973-78dada22-7988-11e8-9049-694846c414ea.png">

As you can see, basically no memory is used after the compression step. Meaning that we don't "leak" anywhere, it's just that dictionary compression of std::strings is horribly inefficient. That's what we want the fixed strings for.
