### ISSUE TITLE
ServerTests print and take some time

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#852]
Just a quick query whether we can do something about this. ServerTestRunner takes 2,5s here (1/3 of total test runtime). Can we lower this? 
Also it prints "Server running on port...". Does it have to? Cluttering test output isn't ideal.

**Comment by lawben** [comment]
The output can be removed. It was/is mainly for debugging purposes, because there is currently no other way to see on which port the server is running. But if that is not important, we can remove it. 

The timing is a little more tricky. We can maybe reduce it a bit, but there needs to be some buffer time in each test before we kill the server. That was one of the main issues I had with these tests. If we kill the socket before everything is finished by the server, we get weird errors and this causes the tests to fail because of e.g. segfaults. I can try and figure out if this time can be reduced to like 100ms instead of 500 (which is pretty defensive, but I don't want to have flakey tests because of it).

Suggestion would be to move the tests to hyriseSystemTest. That is only run in CI, so it's covered. But most people don't care about these tests.

**Comment by mrzzzrm** [comment]
Testing the server in hyriseSystemTest seems to be an approach that makes perfect sense to me.

**Comment by lawben** [comment]
Ok, do you wanna do this quickly? I'm currently busy with something else and probably won't work on this until the weekend.

**Comment by mrzzzrm** [comment]
would, except that there are like 10 things I'd like to do "quickly". :stuck_out_tongue_winking_eye:
