### ISSUE TITLE
hyriseConsole table printing: umlauts mess with print format

### ISSUE THREAD

**Issue by dimitri-schmidt** [hyrise/hyrise#910]
In the context of printing a table in hyriseConsole with a SELECT statement:

Values with umlauts mess with the alignment: for every umlaut the cell gets one character smaller.

Example:

```
SELECT * FROM nation WHERE n_nationkey > 49;
=== Columns
|n_nationkey|              n_name|n_regionkey|           n_comment|
|        int|              string|        int|              string|
=== Chunk 0 === 
|         50|          no umlauts|        500|    still no umlauts|
|         50|string with no um...|        500|still no umlauts ...|
|         50|         1 umlaut ä|        500|           no umlaut|
|         50|     3 umlaut öäü|        500|           no umlaut|
|         50|           no umlaut|        500|       2 umlaut öä|
|         50|       2 umlaut üö|        500|         1 umlaut ü|
|         51|           no umlaut|        500|           no umlaut|
===
7 rows total (COMPILE: 194 µs, EXECUTE: 4509582 µs (wall time))
```

**Comment by mrks** [comment]
This is because they take two bytes in UTF-8. Fixing it here would not be an issue, but we would also have to consider things like `LEN('ümläut')`. Unless @mrzzzrm already thought of that, it would return 8. Even worse if you tried to get the first character.

I don't see anything good out of trying to deal with this.
